//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commerce_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Store
    {
        public int Item_iD { get; set; }
        public string Store_Name { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Item_Name { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Store Store { get; set; }
    }
}
