//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commerce_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items_PurchaseOrder
    {
        public int PurchaseOrder_ID { get; set; }
        public int Item_ID { get; set; }
        public int Qty { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Purchase_Order Purchase_Order { get; set; }
    }
}
