//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commerce_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Item_MesurementValues = new HashSet<Item_MesurementValues>();
            this.Item_Store = new HashSet<Item_Store>();
            this.Items_PayOrder = new HashSet<Items_PayOrder>();
            this.Items_PurchaseOrder = new HashSet<Items_PurchaseOrder>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Production_date { get; set; }
        public System.DateTime Expiry_date { get; set; }
        public int shelf_life { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_MesurementValues> Item_MesurementValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Store> Item_Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items_PayOrder> Items_PayOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items_PurchaseOrder> Items_PurchaseOrder { get; set; }
    }
}
